name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm ci
        working-directory: src/server
      - name: npm test
        env:
          CI: true
          DEV_DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
        run: npm test
        working-directory: src/server
  
